# Generated by Django 5.2.4 on 2025-07-24 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='test_platform',
        ),
        migrations.RemoveField(
            model_name='teststatus',
            name='id',
        ),
        migrations.AddField(
            model_name='app',
            name='test_platforms',
            field=models.ManyToManyField(related_name='apps', to='testing_core.testplatform'),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='fake_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fakeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='app',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='testing_core.app'),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='test_status_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teststatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='teststatus',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='testing_core.test'),
        ),
    ]
