# Generated by Django 5.2.4 on 2025-08-01 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_core', '0003_alter_testcontext_connection_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='fakeUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='testing_core.fakeuser'),
        ),
    ]
