# Generated by Django 5.2.4 on 2025-08-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_core', '0004_alter_test_fakeuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teststatus',
            name='app',
        ),
        migrations.RemoveField(
            model_name='teststatus',
            name='test_status_id',
        ),
        migrations.RemoveField(
            model_name='teststatus',
            name='user',
        ),
        migrations.AddField(
            model_name='teststatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teststatus',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('ready', 'Listo para aplicarse'), ('archived', 'Archivado')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='teststatus',
            name='test',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='testing_core.test'),
        ),
    ]
