# Generated by Django 5.2.4 on 2025-08-04 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing_core', '0005_remove_teststatus_app_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCommit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado')], default='pending', max_length=20)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='testing_core.test')),
                ('test_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit', to='testing_core.testresult')),
            ],
        ),
        migrations.DeleteModel(
            name='TestStatus',
        ),
    ]
